#version: '3.8'

services:
  db:
    image: postgres:latest
    container_name: postgres_db
    environment:
      - POSTGRES_DB=t_m_s
      - POSTGRES_USER=tms_user
      - POSTGRES_PASSWORD=tms_admin
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U tms_user -d t_m_s" ]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 15s
    ports:
      - 5432:5432
    #  volumes:
    #    - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  tms:
    build:
      context: .
    container_name: tms_backend
    depends_on:
      db:
        condition: service_healthy
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/t_m_s
      - SPRING_DATASOURCE_USERNAME=tms_user
      - SPRING_DATASOURCE_PASSWORD=tms_admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=validate
      - SPRING_LIQUIBASE_CHANGE_LOG=classpath:liquibase/changelog-master.yml
    ports:
      - 9090:9090
    networks:
      - backend

  auth:
    build:
      context: ..\tms-auth-server
    container_name: tms_auth_server
    depends_on:
      db:
        condition: service_healthy
      tms:
        condition: service_started
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/t_m_s
      - SPRING_DATASOURCE_USERNAME=tms_user
      - SPRING_DATASOURCE_PASSWORD=tms_admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    networks:
      - backend

#volumes:
#  postgres_data:

networks:
  backend:
    driver: bridge